Repository stolostron/search-v2-operator, pull requests merged in 2022-06, with the labels that each got.

#41 Update images to latest snapshot
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, lgtm, approved

#42 Update readme
  README.md
Labels: dco-signoff: yes, lgtm, approved, stale

#43 updated to latest crd
  bundle/manifests/search.open-cluster-management.io_searches.yaml
Labels: dco-signoff: yes, lgtm, approved

#44 no op PR
  README.md
Labels: dco-signoff: yes, approved

#45 no op pr
  README.md
Labels: dco-signoff: yes, approved

#47 Attempt to substitute image
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, lgtm, approved

#48 updated to latest tags
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#50 Update RBAC doc
  docs/RBAC.md
Labels: dco-signoff: yes, lgtm, approved

#51 update prometheus client golang library for static scan
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved
