Repository stolostron/search-v2-operator, pull requests merged in 2022-11, with the labels that each got.

#86 added composite index,cluster,hubCluster indices
  controllers/create_pgconfigmap.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#88 Add status to Search CR
  controllers/common.go
  controllers/create_pgsecret.go
  controllers/search_controller.go
  controllers/search_test.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#90 Add pods to role list
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, lgtm, approved

#87 first push to use the CSV
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/common.go
  controllers/common_test.go
  controllers/create_pgconfigmap.go
  controllers/create_pgdeployment.go
  controllers/search_test.go
Labels: dco-signoff: yes, lgtm, approved, stale
