Repository stolostron/search-v2-operator, pull requests merged in 2022-03, with the labels that each got.

#7 added serviceaccount for deployments
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/common.go
  controllers/create_collectordeployment.go
  controllers/create_indexerdeployment.go
  controllers/create_rolesbindings.go
  controllers/create_serviceaccount.go
  controllers/ocmsearch_controller.go
  controllers/ocmsearch_test.go
Labels: do-not-merge/hold, dco-signoff: no, approved

#8 make clusterrole for search collector
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/create_rolesbindings.go
  controllers/ocmsearch_controller.go
  controllers/ocmsearch_test.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#9 Updating API-IMAGE
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, approved

#10 fixed the service account for api
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/create_apideployment.go
  controllers/create_indexerservice.go
Labels: dco-signoff: yes, lgtm, approved

#12 Update readme file
  README.md
Labels: dco-signoff: no, lgtm, approved

#13 Watch resources and customize
  api/v1alpha1/search_types.go
  bundle/manifests/search.open-cluster-management.io_searches.yaml
  config/crd/bases/search.open-cluster-management.io_searches.yaml
  controllers/common.go
  controllers/create_apideployment.go
  controllers/create_apiservice.go
  controllers/create_cacert.go
  controllers/create_collectordeployment.go
  controllers/create_indexerconfigmap.go
  controllers/create_indexerdeployment.go
  controllers/create_indexerservice.go
  controllers/create_pgdeployment.go
  controllers/create_pgsecret.go
  controllers/create_pgservice.go
  controllers/create_rolesbindings.go
  controllers/create_serviceaccount.go
  controllers/defaults.go
  controllers/search_controller.go
Labels: dco-signoff: no, approved

#14 added common tests
  controllers/common.go
  controllers/common_test.go
Labels: dco-signoff: yes, lgtm, approved

#17 Add new env var POD_NAMESPACE for collector deployment
  controllers/create_collectordeployment.go
Labels: dco-signoff: yes, lgtm, approved

#18 check for deployment updates
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/common.go
Labels: dco-signoff: yes, approved

#19 removed secret from log
  controllers/common.go
Labels: dco-signoff: yes, lgtm, approved
