Repository stolostron/search-v2-operator, pull requests merged in 2022-08, with the labels that each got.

#59 Update to RBAC Doc - managed cluster cache
  docs/RBAC.md
Labels: dco-signoff: yes, lgtm, approved, stale

#60 Add table trigger for intercluster edge building
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  controllers/create_pgconfigmap.go
  controllers/create_rolesbindings.go
Labels: dco-signoff: yes, lgtm, approved

#64 Architecture Diagram
  docs/Search-Architecture-Diagram.jpeg
  docs/Search-Architecture-Diagram.key
Labels: dco-signoff: yes, lgtm, approved

#65 Update OWNERS and trigger prow to publish 2.7
  OWNERS
Labels: dco-signoff: yes, lgtm, approved

#63 Remove clustermanagementaddon CR search-collector if search is removed
  controllers/cleanup.go
  controllers/search_controller.go
  controllers/search_test.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#66 remove Clusterroles when CR instance if deleted
  controllers/cleanup.go
  controllers/search_controller.go
  controllers/search_test.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#67 Added script to update bundle image versions
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  scripts/BUNDLE_CHANGELOG.md
  scripts/bundle-image-pickup.sh
Labels: dco-signoff: yes, lgtm, approved

#68 Update images to latest
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, lgtm, approved

#69 added toleration support and reconcile fix
  api/v1alpha1/search_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/search.open-cluster-management.io_searches.yaml
  controllers/common.go
  controllers/common_test.go
  controllers/create_apideployment.go
  controllers/create_collectordeployment.go
  controllers/create_indexerdeployment.go
  controllers/create_pgconfigmap.go
  controllers/create_pgdeployment.go
  controllers/search_controller.go
Labels: dco-signoff: yes, lgtm, approved
