Repository stolostron/search-v2-operator, pull requests merged in 2022-09, with the labels that each got.

#70 updated latest bundle image
  README.md
Labels: dco-signoff: yes, lgtm, approved

#71 Add permission to impersonate service account
  controllers/create_rolesbindings.go
Labels: dco-signoff: yes, lgtm, approved

#73 Updated readme file
  README.md
Labels: do-not-merge/hold, dco-signoff: no, lgtm, approved

#74 update helm pkg
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved

#75 Update roles - allow impersonate using uid
  controllers/create_rolesbindings.go
Labels: dco-signoff: yes, lgtm, approved

#76 perf improvements and klusterlet customizations
  addon/addon.go
  addon/addon_test.go
  addon/manifests/chart/Chart.yaml
  addon/manifests/chart/templates/deployment.yaml
  addon/manifests/chart/values.yaml
  controllers/common.go
  controllers/common_test.go
  controllers/search_controller.go
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved
