Repository stolostron/search-v2-operator, pull requests merged in 2023-04, with the labels that each got.

#117 update packages
  .gitignore
  Dockerfile
  Makefile.prow
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved

#120 [release 2.7] ACM-3721 update package
  Dockerfile
  Makefile.prow
  go.mod
  go.sum
Labels: do-not-merge/hold, dco-signoff: yes, lgtm, approved

#119 ACM-3108 add envvar to CRD
  Makefile
  api/v1alpha1/search_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/search.open-cluster-management.io_searches.yaml
  config/crd/bases/search.open-cluster-management.io_searches.yaml
Labels: dco-signoff: yes, lgtm, approved

#121 ACM-3108 add env var to search deployments
  api/v1alpha1/groupversion_info.go
  controllers/common.go
  controllers/common_test.go
  controllers/create_apideployment.go
  controllers/create_collectordeployment.go
  controllers/create_indexerdeployment.go
  controllers/create_pgconfigmap.go
  controllers/create_pgdeployment.go
  controllers/search_test.go
Labels: dco-signoff: yes, lgtm, approved

#118 Added the ability to deploy to a normal kubernetes cluster.
  Makefile
  controllers/common.go
  scripts/deploy.sh
Labels: dco-signoff: yes, lgtm, approved, ok-to-test

#123 [ACM-4632] remove mch node toleration and selector from addondeploymentconfig
  addon/manifests/chart/values.yaml
  controllers/create_addondeploymentconfig.go
Labels: dco-signoff: yes, lgtm, approved
